package synthrepo

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"math/rand/v2"
	"path"
	"slices"
	"strconv"
	"strings"

	"github.com/GiulioSavini/gruntled/internal/domain/diagnostic"
	"github.com/GiulioSavini/gruntled/internal/domain/repograph"
)

// header is the first line of every generated file.
const header = "# Generated by gruntled synthrepo. Do not edit.\n"

// File is one file in a generated Tree.
type File struct {
	// Path is the repo-relative, slash-separated path.
	Path string
	// Content is the file's exact bytes.
	Content []byte
}

// Tree is a generated repository's files, sorted by Path.
type Tree []File

// Digest returns a hex-encoded SHA-256 over the tree: for each file, in
// Path order, Path + "\x00" + Content + "\x00". Two trees produced by
// Render from the same Spec and Seed always have the same Digest, on any
// run, on any process.
func (t Tree) Digest() string {
	h := sha256.New()
	for _, f := range t {
		h.Write([]byte(f.Path))
		h.Write([]byte{0})
		h.Write(f.Content)
		h.Write([]byte{0})
	}
	return hex.EncodeToString(h.Sum(nil))
}

// unitInfo holds what Render decides about one unit before rendering any
// bytes: its directory path and declared outputs.
type unitInfo struct {
	path    string
	outputs []string
}

// reference is one dependency.X.outputs.Y reference, in the order Render
// discovers it (unit index, then dependency order). output may be
// rewritten in place by the injection step.
type reference struct {
	unitIndex   int
	depName     string
	targetIndex int
	output      string
	inputKey    string
}

// Render is a pure function from Spec to an in-memory Tree and Manifest.
// It performs no I/O. The same Spec and Seed always produce a
// reflect.DeepEqual Tree and Manifest, on any run, on any process.
//
// Render consumes its *rand.Rand in exactly this order; changing the
// order changes every digest:
//  1. For each unit, in index order: IncludeDepth-1 group-selection
//     draws (rng.IntN(2) each), then one output-count draw
//     (rng.IntN(3)).
//  2. For each unit, in index order: one rng.Perm(i) draw for dependency
//     target selection, then one rng.IntN output-selection draw per
//     dependency, in ascending target-index order.
//  3. For each injected error, in spec.Errors order: one rng.IntN draw
//     selecting which not-yet-corrupted reference to corrupt.
func Render(spec Spec) (Tree, Manifest, error) {
	if err := spec.Validate(); err != nil {
		return nil, Manifest{}, err
	}

	rng := rand.New(rand.NewPCG(uint64(spec.Seed), 0x9E3779B97F4A7C15))

	width := max(3, len(strconv.Itoa(spec.Units-1)))

	// Phase 1: unit identity and output surface, in index order.
	units := make([]unitInfo, spec.Units)
	for i := 0; i < spec.Units; i++ {
		name := fmt.Sprintf("unit-%0*d", width, i)
		groups := make([]string, spec.IncludeDepth-1)
		for g := 0; g < spec.IncludeDepth-1; g++ {
			groups[g] = fmt.Sprintf("g%d", rng.IntN(2))
		}
		unitPath := path.Join(append(groups, name)...)

		outputCount := 1 + rng.IntN(3)
		outputs := make([]string, outputCount)
		for o := 0; o < outputCount; o++ {
			outputs[o] = fmt.Sprintf("out_%d", o)
		}

		units[i] = unitInfo{path: unitPath, outputs: outputs}
	}

	// Phase 2: dependency edges, acyclic by construction (unit i only
	// depends on units with index < i).
	unitRefs := make([][]int, spec.Units) // unit index -> indices into allRefs
	var allRefs []reference
	for i := 0; i < spec.Units; i++ {
		k := min(spec.DependencyFanout, i)
		perm := rng.Perm(i)
		targets := append([]int(nil), perm[:k]...)
		slices.Sort(targets)

		for _, j := range targets {
			depName := fmt.Sprintf("dep_%0*d", width, j)
			outIdx := rng.IntN(len(units[j].outputs))
			output := units[j].outputs[outIdx]
			inputKey := fmt.Sprintf("in_%s_%s", depName, output)

			unitRefs[i] = append(unitRefs[i], len(allRefs))
			allRefs = append(allRefs, reference{
				unitIndex:   i,
				depName:     depName,
				targetIndex: j,
				output:      output,
				inputKey:    inputKey,
			})
		}
	}

	// Phase 3: injections.
	badOutputCount := 0
	for _, e := range spec.Errors {
		if e == BadOutputRef {
			badOutputCount++
		}
	}
	if badOutputCount > len(allRefs) {
		return nil, Manifest{}, fmt.Errorf("synthrepo: cannot inject %d BadOutputRef error(s): tree has only %d reference(s)", badOutputCount, len(allRefs))
	}

	corrupted := make(map[int]struct{}, badOutputCount)
	remaining := make([]int, len(allRefs))
	for i := range remaining {
		remaining[i] = i
	}
	ordinal := 0
	for _, e := range spec.Errors {
		if e != BadOutputRef {
			continue
		}
		pick := rng.IntN(len(remaining))
		refIdx := remaining[pick]
		remaining = append(remaining[:pick], remaining[pick+1:]...)

		allRefs[refIdx].output = fmt.Sprintf("missing_out_%d", ordinal)
		corrupted[refIdx] = struct{}{}
		ordinal++
	}

	// Phase 4: render bytes.
	tree := make(Tree, 0, 1+2*spec.Units)
	var expected []ExpectedDiagnostic

	tree = append(tree, File{
		Path:    "root.hcl",
		Content: []byte(fmt.Sprintf("%sinputs = {\n  synthrepo_seed = \"%d\"\n}\n", header, spec.Seed)),
	})

	for i := 0; i < spec.Units; i++ {
		u := units[i]
		tgFile := path.Join(u.path, "terragrunt.hcl")
		refIdxs := unitRefs[i]

		var buf bytes.Buffer
		buf.WriteString(header)
		buf.WriteString("include \"root\" {\n")
		buf.WriteString("  path = find_in_parent_folders(\"root.hcl\")\n")
		buf.WriteString("}\n")

		for _, refIdx := range refIdxs {
			r := allRefs[refIdx]
			target := units[r.targetIndex]
			buf.WriteString("\n")
			buf.WriteString(fmt.Sprintf("dependency \"%s\" {\n", r.depName))
			buf.WriteString(fmt.Sprintf("  config_path = \"%s\"\n", relPath(u.path, target.path)))
			buf.WriteString("}\n")
		}

		type refOffset struct {
			refIdx int
			offset int
		}
		var offsets []refOffset

		if len(refIdxs) > 0 {
			buf.WriteString("\n")
			buf.WriteString("inputs = {\n")
			for _, refIdx := range refIdxs {
				r := allRefs[refIdx]
				buf.WriteString(fmt.Sprintf("  %s = ", r.inputKey))
				offsets = append(offsets, refOffset{refIdx: refIdx, offset: buf.Len()})
				buf.WriteString(fmt.Sprintf("dependency.%s.outputs.%s\n", r.depName, r.output))
			}
			buf.WriteString("}\n")
		}

		content := buf.Bytes()

		for _, ro := range offsets {
			if _, ok := corrupted[ro.refIdx]; !ok {
				continue
			}
			r := allRefs[ro.refIdx]
			line, col := lineCol(content, ro.offset)
			pos, err := repograph.NewPosition(repograph.MustRepoPath(tgFile), line, col)
			if err != nil {
				return nil, Manifest{}, fmt.Errorf("synthrepo: internal error building position: %w", err)
			}
			expected = append(expected, ExpectedDiagnostic{
				Code:       diagnostic.CodeUnknownOutput,
				Pos:        pos,
				Unit:       repograph.MustRepoPath(u.path),
				Dependency: r.depName,
				Target:     repograph.MustRepoPath(units[r.targetIndex].path),
				Output:     r.output,
			})
		}

		tree = append(tree, File{Path: tgFile, Content: content})

		var mainBuf bytes.Buffer
		mainBuf.WriteString(header)
		for _, refIdx := range refIdxs {
			r := allRefs[refIdx]
			mainBuf.WriteString("\n")
			mainBuf.WriteString(fmt.Sprintf("variable \"%s\" {\n", r.inputKey))
			mainBuf.WriteString("  type = string\n")
			mainBuf.WriteString("}\n")
		}
		for _, out := range u.outputs {
			mainBuf.WriteString("\n")
			mainBuf.WriteString(fmt.Sprintf("output \"%s\" {\n", out))
			mainBuf.WriteString(fmt.Sprintf("  value = \"%s/%s\"\n", u.path, out))
			mainBuf.WriteString("}\n")
		}

		tree = append(tree, File{Path: path.Join(u.path, "main.tf"), Content: mainBuf.Bytes()})
	}

	slices.SortFunc(tree, func(a, b File) int { return strings.Compare(a.Path, b.Path) })

	unitPaths := make([]repograph.RepoPath, spec.Units)
	for i, u := range units {
		unitPaths[i] = repograph.MustRepoPath(u.path)
	}
	slices.SortFunc(unitPaths, func(a, b repograph.RepoPath) int { return a.Compare(b) })

	slices.SortFunc(expected, func(a, b ExpectedDiagnostic) int { return a.Pos.Compare(b.Pos) })

	return tree, Manifest{Units: unitPaths, Expected: expected}, nil
}

// relPath returns the slash-separated relative path from the directory
// from to the directory to: a sequence of ".." segments crossing up to
// their common ancestor, followed by whatever remains of to below it.
// Pure string manipulation over already-clean, slash-separated repo
// paths; render.go does no I/O and never imports path/filepath.
func relPath(from, to string) string {
	fromParts := strings.Split(from, "/")
	toParts := strings.Split(to, "/")

	common := 0
	for common < len(fromParts) && common < len(toParts) && fromParts[common] == toParts[common] {
		common++
	}

	parts := make([]string, 0, (len(fromParts)-common)+(len(toParts)-common))
	for i := common; i < len(fromParts); i++ {
		parts = append(parts, "..")
	}
	parts = append(parts, toParts[common:]...)

	return strings.Join(parts, "/")
}

// lineCol returns the 1-based line and column (column counted in bytes)
// of the byte at offset within content.
func lineCol(content []byte, offset int) (line, col int) {
	line = 1
	lastNewline := -1
	for i := 0; i < offset && i < len(content); i++ {
		if content[i] == '\n' {
			line++
			lastNewline = i
		}
	}
	return line, offset - lastNewline
}
