// Package synthrepo deterministically generates synthetic Terragrunt
// repository trees for use as test fixtures by Phases 2-4. It lives outside
// internal/domain, internal/application, internal/infrastructure and
// internal/interfaces: it writes files (os, path/filepath), which is its
// job, but it must never be imported by cmd/gruntled or by any non-test
// file of a production package. scripts/check-architecture.sh enforces
// that on the cmd side.
//
// # Generated layout
//
// Given a Spec, the generator produces a tree rooted at the destination
// directory:
//
//	root.hcl                        one per tree, shared by every unit
//	<group.../>unit-<NNN>/
//	    terragrunt.hcl               include block, dependency blocks, inputs
//	    main.tf                      variable blocks, output blocks
//
// root.hcl is a single file at the tree root:
//
//	# Generated by gruntled synthrepo. Do not edit.
//	inputs = {
//	  synthrepo_seed = "<seed>"
//	}
//
// Units are inline: the unit directory equals the module directory, and
// there is no terraform.source attribute. Unit != Module generation is
// deferred to a later phase.
//
// Each unit's directory path has exactly Spec.IncludeDepth path segments:
// IncludeDepth-1 group segments named "g0" or "g1", chosen pseudo-randomly,
// followed by the unit's own directory, named "unit-<NNN>" with NNN
// zero-padded to at least 3 digits (wider if Spec.Units-1 needs more).
// Every unit includes the single shared root.hcl via
// find_in_parent_folders("root.hcl"), regardless of how many group
// segments separate it from the root.
//
// Unit i (0-based, in generation order, not directory-name order) may
// depend on any unit with a lower index: up to min(Spec.DependencyFanout,
// i) of them, chosen pseudo-randomly and referenced through a Terragrunt
// dependency block. This makes the dependency graph acyclic by
// construction. Unit 0 never has dependency blocks.
//
// Each dependency reference takes the form
// dependency.<dep>.outputs.<out> inside the unit's inputs block, where
// <dep> is the dependency block's label (dep_<NNN>, zero-padded like unit
// names) and <out> is one of the target unit's declared outputs
// (out_0..out_{n-1}). The position semantics for
// synthrepo.ExpectedDiagnostic.Pos point at the byte offset of the "d" in
// "dependency" for that specific reference, inside the referencing unit's
// terragrunt.hcl, using 1-based lines and 1-based, byte-counted columns.
//
// Spec.Errors injects deliberate mutations. The only implemented kind is
// BadOutputRef: it rewrites one reference's <out> to a name
// ("missing_out_<N>") that the target module does not declare, leaving
// the input key and consuming variable name untouched, so the mutation
// looks like a single-token rename bug. Render's returned Manifest lists
// exactly the references mutated this way; every other reference in the
// tree is valid, so the Manifest is the exact oracle a correct analyzer
// must reproduce.
package synthrepo

import "fmt"

// ErrorKind identifies a kind of deliberate mutation Render/Generate can
// inject into an otherwise-valid synthetic repository.
type ErrorKind int

const (
	// BadOutputRef rewrites one dependency.X.outputs.Y reference to name
	// an output the target module does not declare.
	BadOutputRef ErrorKind = iota + 1
)

// String renders the error kind as a short, stable, lowercase label.
func (k ErrorKind) String() string {
	switch k {
	case BadOutputRef:
		return "bad-output-ref"
	default:
		return fmt.Sprintf("ErrorKind(%d)", int(k))
	}
}

// Spec parameterizes a synthetic Terragrunt repository.
type Spec struct {
	// Units is the number of unit directories to generate. Must be >= 1.
	Units int
	// IncludeDepth is the number of directory levels between the repo
	// root, where the single shared root.hcl lives, and each unit
	// directory. Must be >= 1.
	IncludeDepth int
	// DependencyFanout is the maximum number of dependency blocks any
	// unit gets: unit i gets min(DependencyFanout, i) dependencies on
	// lower-index units. Must be >= 0.
	DependencyFanout int
	// Seed is the PRNG seed. The same Spec and Seed always produce a
	// byte-identical tree.
	Seed int64
	// Errors lists deliberate mutations to inject, one instance per
	// entry, applied in order.
	Errors []ErrorKind
}

// Validate reports whether s's fields are structurally well-formed. It
// does not check whether s.Errors can actually be satisfied by the
// generated tree (e.g. more BadOutputRef entries than references exist);
// that check happens in Render, since it depends on the generated shape.
func (s Spec) Validate() error {
	if s.Units < 1 {
		return fmt.Errorf("synthrepo: invalid spec: Units must be >= 1, got %d", s.Units)
	}
	if s.IncludeDepth < 1 {
		return fmt.Errorf("synthrepo: invalid spec: IncludeDepth must be >= 1, got %d", s.IncludeDepth)
	}
	if s.DependencyFanout < 0 {
		return fmt.Errorf("synthrepo: invalid spec: DependencyFanout must be >= 0, got %d", s.DependencyFanout)
	}
	for i, e := range s.Errors {
		if e != BadOutputRef {
			return fmt.Errorf("synthrepo: invalid spec: Errors[%d] is not a known ErrorKind: %d", i, int(e))
		}
	}
	return nil
}
